-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 09.02.2014 16:38:45
-- Server version: 5.6.12
-- Client version: 4.1

DROP DATABASE IF EXISTS `mok.shop`;
CREATE DATABASE IF NOT EXISTS `mok.shop`
CHARACTER SET utf8
COLLATE utf8_general_ci;

USE `mok.shop`;

CREATE TABLE IF NOT EXISTS t_categories (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS t_marks (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS t_product_description (
  id int(11) NOT NULL AUTO_INCREMENT,
  product_id int(11) NOT NULL,
  name varchar(50) DEFAULT NULL,
  price decimal(19, 2) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_t_product_description_t_products_id FOREIGN KEY (product_id)
  REFERENCES t_products (id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS t_products (
  id int(11) NOT NULL AUTO_INCREMENT,
  owner int(11) NOT NULL,
  category int(11) NOT NULL,
  mark int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_t_products_t_marks_id FOREIGN KEY (mark)
  REFERENCES t_marks (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_t_products_t_sub_categories_id FOREIGN KEY (category)
  REFERENCES t_sub_categories (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_t_products_t_users_id FOREIGN KEY (owner)
  REFERENCES t_users (id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS t_sub_categories (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  parent_category int(11) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_t_sub_categories_t_categories_id FOREIGN KEY (parent_category)
  REFERENCES t_categories (id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS t_users (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  is_admin tinyint(4) NOT NULL DEFAULT 0,
  email varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 12
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci;