-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.622.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 18.01.2014 17:33:43
-- Server version: 5.6.12
-- Client version: 4.1

DROP DATABASE IF EXISTS `mok.shop`;
CREATE DATABASE IF NOT EXISTS `mok.shop`
CHARACTER SET utf8
COLLATE utf8_general_ci;

USE `mok.shop`;

CREATE TABLE IF NOT EXISTS t_users (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) DEFAULT NULL,
  is_admin tinyint(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;